// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQtKlp88bA1LmZoS2GFdntVYwaRZNqzX0',
    appId: '1:416420345950:web:5ba6ffc98bdb87dd889ccf',
    messagingSenderId: '416420345950',
    projectId: 'fir-app-69067',
    authDomain: 'fir-app-69067.firebaseapp.com',
    storageBucket: 'fir-app-69067.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5YKkNxnjkBRBoeyX8K-YywqpnicU9XjM',
    appId: '1:416420345950:android:a673ba3fb005e3ff889ccf',
    messagingSenderId: '416420345950',
    projectId: 'fir-app-69067',
    storageBucket: 'fir-app-69067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Cc6_s7CMPmgD9HSslWwOFO3s6PXRB70',
    appId: '1:416420345950:ios:b12a45e771253dd1889ccf',
    messagingSenderId: '416420345950',
    projectId: 'fir-app-69067',
    storageBucket: 'fir-app-69067.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Cc6_s7CMPmgD9HSslWwOFO3s6PXRB70',
    appId: '1:416420345950:ios:b12a45e771253dd1889ccf',
    messagingSenderId: '416420345950',
    projectId: 'fir-app-69067',
    storageBucket: 'fir-app-69067.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQtKlp88bA1LmZoS2GFdntVYwaRZNqzX0',
    appId: '1:416420345950:web:70a08c0a0e2c52d6889ccf',
    messagingSenderId: '416420345950',
    projectId: 'fir-app-69067',
    authDomain: 'fir-app-69067.firebaseapp.com',
    storageBucket: 'fir-app-69067.firebasestorage.app',
  );
}
